##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: LoanApplicationApi
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

adapters:
  r2dbc:
    host: "${R2DBC_HOST}"
    port: "${R2DBC_PORT}"
    database: "${R2DBC_DATABASE}"
    schema: "${R2DBC_SCHEMA}"
    username: "${R2DBC_USERNAME}"
    password: "${R2DBC_PASSWORD}"